### PR TITLE
Make more efficient.

### PR DESCRIPTION
**Pull request by theitsmith**
Updated to use the `Minifier` class to improve efficiency: [htmlmin.Minifier](https://htmlmin.readthedocs.org/en/latest/reference.html#htmlmin.Minifier)

### CODE REVIEW

**Comment by hamidfzm** [comment]
What makes you think it's better? you construct on object in every request!!!

**Comment by theitsmith** [comment]
According to the developer's website (referring to the `Minifier` class as linked above):

> If you are going to be minifying multiple pieces of HTML, this will be more efficient than using htmlmin.minify.

So my code could use some improvement, but the idea remains. I'm learning to work with Python classes and am not yet too familiar with `@staticmethod`s and such.

However, the improvements I made were to move the constructor to `__init__()` and to remove the `@staticmethod` declaration from `response_minify()`. The abridged changes are:

    def __init__(...):
        ...
        self.html_minify = Minifier(...)

    def response_minify(self, response):
        ...
        self.html_minify.minify(...) 

Thoughts?

**Comment by runartrollet** [comment]
Note that this could break some sites, as they do work a bit different.

**Comment by theitsmith** [comment]
Example?

**Comment by runartrollet** [comment]
haven't quite figured out what is causing it at the moment. might be an error with htmlmin, really. Currently, I get errors with unclosed tags, when used with google oauth. These errors do not occur when using `minify` instead of `Minifier.minify`. Needs more attention.

**Comment by theitsmith** [comment]
Without specifics, it's difficult to evaluate the problem. But as this project is just a wrapper around htmlmin, the issue is more likely upstream or with the code you're trying to minify.

**Comment by runartrollet** [comment]
When running `Minifier.minify`, it does some extra parsing, which does not happen in `minify`. I agree that this is a problem with upstream.

**Pull request merged**
